title: "CMMC"
description: "Study notes on modern cryptography."
# theme: minima
# theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0

url: "https://cyc6221.github.io"
baseurl: "/CMMC"

# Author info
author: CY
email: s24343162@gmail.com
github_username: cyc6221
linkedin_url: https://www.linkedin.com/in/ching-yeh-chen-348a513ba/

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  articles:
    output: true
    permalink: /articles/:path/

header_pages:
  # - index.md
  - pages/about.md
  - pages/articles.md
  - pages/tags.md

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-remote-theme

sitemap:
  path: sitemap.xml
